import { Artwork, Exhibition, PaletteColor, Award } from './types';

export const ARTWORKS: Artwork[] = [
  // CATEGORY 1 — HUMAN EXPERIENCE
  {
    id: 'distance-between-versions',
    title: 'The Distance Between Versions of Me',
    category: 'abstract',
    collectionCategory: 'Human Experience',
    year: '2026',
    medium: 'Oil and Gilded Beeswax on Canvas',
    size: '120 x 120 cm',
    dimensions: '120 x 120 cm',
    description: 'A striking study of self-reflection and fragmented identity, using mirrored silhouettes dissolving into abstract textured strokes.',
    story: 'This piece explores the quiet chasms that form within our own life timelines. It represents the confrontation between who we were, who we are, and who we hope to become.',
    storyBehindPainting: 'Painted during a period of deep self-isolation, this work represents two spectral figures facing each other across a textured, golden-leaf divide. The division line is a physical scar of impasto on the canvas, showing the friction of personal evolution.',
    artistReflection: 'Every year, we shed a skin we thought was permanent. When I look at this painting, I do not see two different people; I see the bridge made of light and shadow that connects them.',
    symbolAnalysis: 'The dual silhouetted figures represent the temporal self. The gold-leaf accent line down the center is the Golden Thread of awareness, symbolizing the persistent soul that survives change.',
    relatedWorks: ['The Cost of Becoming', 'Self-Awareness'],
    inspirationNotes: 'Inspired by the solo piano works of Philip Glass, repeating simple patterns that slowly shift in key over time.',
    colorPaletteInfo: 'Underlaid with deep Prussian Blue, built up with Raw Sienna glazes, and finished with 24k genuine gold leaf gilding.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)', 'Atmospheric Mirrors, Paris (2026)'],
    image: '/src/assets/images/sea_cliff_1782318218612.jpg',
    price: '€5,800',
    available: true,
    featured: true,
    colors: ['prussian-blue', 'raw-sienna', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'borrowed-time',
    title: 'Borrowed Time',
    category: 'still-life',
    collectionCategory: 'Human Experience',
    year: '2026',
    medium: 'Oil on Gessoed Board',
    size: '60 x 60 cm',
    dimensions: '60 x 60 cm',
    description: 'An intimate interior scene dominated by a towering grandfather clock with a glowing golden bird resting on its hand.',
    story: 'A meditation on the impermanence of our days. It captures a fleeting moment where time itself stands still to marvel at life.',
    storyBehindPainting: 'Influenced by 17th-century Dutch Vanitas, this painting positions an antique wooden clock in deep chiaroscuro shadow, with light source emerging solely from the chest of a small, glowing bird.',
    artistReflection: 'We often treat time as a commodity to spend. But in reality, every hour is a borrowed grace, a temporary loan from the infinite.',
    symbolAnalysis: 'The Clock signifies mortality and the constant ticking of earthly life, while the Golden Bird perched on its hands represents the transcendent hope that exists beyond time.',
    relatedWorks: ['The Bird of Gold', 'Letters Never Delivered'],
    inspirationNotes: 'Sketched in Prague under the winter twilight, listening to the ambient chime of old cathedral bells.',
    colorPaletteInfo: 'Dominant Burnt Umber base, highlights in Cadmium Yellow, and deep Prussian Blue shadows.',
    exhibitionHistory: ['Chiaroscuro & Solitude, London (2025)'],
    image: '/src/assets/images/bird_clock_1782341148172.jpg',
    price: '€3,900',
    available: true,
    featured: true,
    colors: ['raw-sienna', 'cadmium-orange', 'prussian-blue'],
    roomSimulatorCompatible: true
  },
  {
    id: 'inheritance-silence',
    title: 'Inheritance of Silence',
    category: 'still-life',
    collectionCategory: 'Human Experience',
    year: '2025',
    medium: 'Oil on Linen',
    size: '80 x 100 cm',
    dimensions: '80 x 100 cm',
    description: 'A solitary rustic wooden chair sitting in a dark, empty room, with a warm iron lantern casting long shadows across the floorboards.',
    story: 'This painting explores the unseen burdens and quiet lineages passed down through generations—the unspoken griefs and enduring hopes.',
    storyBehindPainting: 'The chair has been a recurring subject of mine. It holds the shape of an absent body. By placing the lantern beside it, I wanted to show that even in the deepest silence of family history, a warm guidance remains.',
    artistReflection: 'Silence is not empty. It has a heavy, textured density, much like layered oil paint. It is often the greatest thing we inherit from those who came before us.',
    symbolAnalysis: 'The Empty Chair represents longing and unfinished conversations. The Lantern stands for guidance, truth, and discovery in darkness.',
    relatedWorks: ['The Weight of Unspoken Words', 'The Last Lantern'],
    inspirationNotes: 'Inspired by memories of my grandfather’s library in Bohemia, where the air was thick with paper and quiet contemplation.',
    colorPaletteInfo: 'Rich Venetian Red glazes, Ivory Black, and warm Sienna undertones.',
    exhibitionHistory: ['Chiaroscuro & Solitude, London (2025)'],
    image: '/src/assets/images/chair_lantern_1782341132046.jpg',
    price: '€4,600',
    available: false,
    featured: false,
    colors: ['raw-sienna', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'noise-stopped',
    title: 'When the Noise Finally Stopped',
    category: 'cityscape',
    collectionCategory: 'Human Experience',
    year: '2025',
    medium: 'Oil and Cold Wax on Canvas',
    size: '120 x 90 cm',
    dimensions: '120 x 90 cm',
    description: 'A moody city street after a storm, where towering concrete facades dissolve into soft, shimmering reflections on wet asphalt.',
    story: 'Capturing the deep, serene peace that descends upon an urban center when the rain clears and the traffic falls silent.',
    storyBehindPainting: 'Berlin after a midnight squall. I waited on a street corner for two hours. The cold wax medium gave the dark asphalt an authentic, damp, semi-matte finish that catches the light reflections like glass.',
    artistReflection: 'In modern life, we are bombarded by noise. The moments when that noise ceases are not just quiet; they are holy. They are when we find our alignment again.',
    symbolAnalysis: 'The wet reflections act as a River of memory, washing away urban debris. The single distant streetlight is a beacon of Purpose and redemption.',
    relatedWorks: ['Neon Echoes on Wet Asphalt', 'The Last Train to Summer'],
    inspirationNotes: 'Listening to Max Richter’s Sleep while working on the concrete gray gradients.',
    colorPaletteInfo: 'Raw Umber, Prussian Blue, Zinc White, and highlights of Cadmium Orange.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)'],
    image: '/src/assets/images/city_rain_1782318233879.jpg',
    price: '€6,100',
    available: true,
    featured: true,
    colors: ['prussian-blue', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'weight-unspoken',
    title: 'The Weight of Unspoken Words',
    category: 'still-life',
    collectionCategory: 'Human Experience',
    year: '2026',
    medium: 'Oil on Gessoed Panel',
    size: '50 x 50 cm',
    dimensions: '50 x 50 cm',
    description: 'A minimalist chiaroscuro composition focusing on a single green pear sitting on a dark ledge, bathed in dramatic side light.',
    story: 'Representing the heavy, silent density of things left unsaid between loved ones, suspended in the space between them.',
    storyBehindPainting: 'A direct homage to Spanish painter Cotán. The pear is rendered with microscopic precision, its skin showing tiny flecks of decay and gold, contrasting with the absolute void of the black background.',
    artistReflection: 'A word withheld has its own physical weight. It sits in the room like an object on a table, occupying space, changing the temperature of the air.',
    symbolAnalysis: 'The Green Pear, isolated in light, represents the organic beauty and delicate fragility of human vulnerability.',
    relatedWorks: ['Solitude of the Green Pear', 'Inheritance of Silence'],
    inspirationNotes: 'Chopin’s Nocturnes on a loop in the studio, painting in the dead of night.',
    colorPaletteInfo: 'Viridian Green, Yellow Ochre, Raw Sienna, and deep carbon black glazes.',
    exhibitionHistory: ['Chiaroscuro & Solitude, London (2025)'],
    image: '/src/assets/images/still_life_pear_1782318248414.jpg',
    price: '€2,400',
    available: true,
    featured: false,
    colors: ['viridian-green', 'raw-sienna', 'titanium-white'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 2 — SPIRITUAL SYMBOLISM
  {
    id: 'third-watch',
    title: 'The Third Watch',
    category: 'seascape',
    collectionCategory: 'Spiritual Symbolism',
    year: '2026',
    medium: 'Oil and Beeswax on Linen',
    size: '140 x 100 cm',
    dimensions: '140 x 100 cm',
    description: 'A vast, turbulent sea under a crescent moon, with waves illuminated by a single distant, glowing lighthouse on the horizon.',
    story: 'Inspired by the ancient biblical concept of the third watch—the darkest hours of the night, just before the first cracks of dawn.',
    storyBehindPainting: 'This painting is about faith when there is no visible proof of morning. I built the ocean waves using layers of glaze mixed with beeswax, giving them a heavy, churning, translucent volume.',
    artistReflection: 'The third watch is when our fears are loudest. But it is also when the spirit is most receptive to the silent signals of light on the horizon.',
    symbolAnalysis: 'The River/Sea represents the passage of time and trials. The Distant Light on the horizon represents redemption, purpose, and the calling home.',
    relatedWorks: ['The Ingress of Ocean Swell', 'The River That Remembers'],
    inspirationNotes: 'Sketched on the windy cliffs of northern Spain during a stormy autumn night.',
    colorPaletteInfo: 'Prussian Blue, Cerulean Blue, Zinc White, and a tiny spot of pure Cadmium Yellow.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/sea_cliff_1782318218612.jpg',
    price: '€6,500',
    available: true,
    featured: true,
    colors: ['prussian-blue', 'titanium-white', 'raw-sienna'],
    roomSimulatorCompatible: true
  },
  {
    id: 'before-rooster-crowed',
    title: 'Before the Rooster Crowed',
    category: 'abstract',
    collectionCategory: 'Spiritual Symbolism',
    year: '2026',
    medium: 'Oil on Canvas',
    size: '100 x 100 cm',
    dimensions: '100 x 100 cm',
    description: 'An abstract, atmospheric arched stone doorway with a dim rooster silhouette standing in a pool of golden dawn light.',
    story: 'Exploring the moment of human failure, betrayal, and the immediate, quiet dawn of grace that follows.',
    storyBehindPainting: 'An architectural fantasy based on old Prague alleys. The stone archway framing the glowing sunrise symbolises the doorway of second chances.',
    artistReflection: 'We all have moments where we fall short of our ideals. The rooster crowing is not just a sign of denial; it is a promise that the sun is rising anyway.',
    symbolAnalysis: 'The Arched Doorway represents transition and spiritual awakening. The Dawn Light represents redemption and the persistent warmth of grace.',
    relatedWorks: ['The Third Watch', 'The Cost of Becoming'],
    inspirationNotes: 'Bach’s St. Matthew Passion, specifically the aria "Erbarme dich, mein Gott".',
    colorPaletteInfo: 'Charcoal Black, Burnt Sienna, Cadmium Orange, and Naples Yellow.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/artist_studio_1782318266342.jpg', // studio image acts as interior/archway
    price: '€5,700',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'fire-refused-consume',
    title: 'The Fire That Refused to Consume',
    category: 'landscape',
    collectionCategory: 'Spiritual Symbolism',
    year: '2026',
    medium: 'Oil and Gold Leaf on Canvas (Heavy Impasto)',
    size: '130 x 95 cm',
    dimensions: '130 x 95 cm',
    description: 'A radiant golden birch forest glowing with surreal orange and yellow fires that leave the leaves and bark unharmed.',
    story: 'A powerful representation of enduring spiritual fire, resilience, and the sacred presence that sustains us through trials.',
    storyBehindPainting: 'Using thick palette knife strokes, I carved a forest where the trees are not burning down, but are themselves made of pure, radiant energy. Golden leaf was applied directly to the bark ridges.',
    artistReflection: 'There are fires in life that destroy, but there is also a fire that purifies and preserves. That is the divine spark within all living things.',
    symbolAnalysis: 'The Forest represents the landscape of self-discovery. The unconsumed fire represents hope, eternal truth, and the presence of the sacred.',
    relatedWorks: ['Whispers of the Gilded Birch', 'The Bird of Gold'],
    inspirationNotes: 'Created in the heat of midsummer, inspired by the concept of the burning bush.',
    colorPaletteInfo: 'Genuine Gold Leaf, Cadmium Orange, Raw Sienna, and Viridian Green.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/autumn_forest_1782318199839.jpg',
    price: '€7,200',
    available: true,
    featured: true,
    colors: ['cadmium-orange', 'raw-sienna', 'viridian-green', 'titanium-white'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 3 — IMAGINARY MEMORIES
  {
    id: 'last-train-summer',
    title: 'The Last Train to Summer',
    category: 'cityscape',
    collectionCategory: 'Imaginary Memories',
    year: '2025',
    medium: 'Oil on Canvas',
    size: '110 x 85 cm',
    dimensions: '110 x 85 cm',
    description: 'An atmospheric railway platform at sunset, with a train pulling away into a golden haze, casting long shadows.',
    story: 'An exploration of nostalgia, departure, and the sweet, lingering melancholy of seasons ending.',
    storyBehindPainting: 'Based on childhood train journeys through Bohemia. The train is a blurred shape, dissolving into the warm atmospheric dust of the sunset, capturing memory rather than steel.',
    artistReflection: 'We are all passengers on trains that only travel in one direction. We cannot return to past summers, but we can preserve their golden warmth on canvas.',
    symbolAnalysis: 'The Sunset represents the closing of a chapter. The Train is the vehicle of time, and the railway platform is a liminal space of choice.',
    relatedWorks: ['Letters Never Delivered', 'The House Beside the River'],
    inspirationNotes: 'Listening to the rhythmic clicking of train tracks during a research journey to Vienna.',
    colorPaletteInfo: 'Yellow Ochre, Venetian Red, Prussian Blue, and Titanium White.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)'],
    image: '/src/assets/images/city_rain_1782318233879.jpg', // city rain acts as train city reflections
    price: '€4,900',
    available: true,
    featured: false,
    colors: ['prussian-blue', 'cadmium-orange', 'raw-sienna'],
    roomSimulatorCompatible: true
  },
  {
    id: 'letters-never-delivered',
    title: 'Letters Never Delivered',
    category: 'still-life',
    collectionCategory: 'Imaginary Memories',
    year: '2025',
    medium: 'Oil on Gessoed Board',
    size: '50 x 40 cm',
    dimensions: '50 x 40 cm',
    description: 'A bundle of old, ribbon-tied parchment letters lying on an antique wooden desk beside a single dried flower.',
    story: 'A tribute to the thoughts we bury, the letters we write but never send, and the silent, parallel lives they build.',
    storyBehindPainting: 'Every family has a drawer of letters that were kept secret. I painted the textures of the old parchment using fine glazes of Burnt Umber, giving them a tactile, brittle quality.',
    artistReflection: 'The letters we do not send are often the most honest. They represent our truest, most unguarded selves, frozen in a state of eternal waiting.',
    symbolAnalysis: 'The Letters signify unspoken truths. The Dried Flower symbolizes memory, fading beauty, and the preservation of love across time.',
    relatedWorks: ['The Weight of Unspoken Words', 'Solitude of the Green Pear'],
    inspirationNotes: 'Reading the personal correspondence of historical artists, finding comfort in their shared doubts.',
    colorPaletteInfo: 'Raw Sienna, Burnt Umber, Flake White, and Prussian Blue.',
    exhibitionHistory: ['Chiaroscuro & Solitude, London (2025)'],
    image: '/src/assets/images/still_life_pear_1782318248414.jpg', // still life style matching
    price: '€2,800',
    available: false,
    featured: false,
    colors: ['raw-sienna', 'titanium-white', 'prussian-blue'],
    roomSimulatorCompatible: true
  },
  {
    id: 'house-beside-river',
    title: 'The House Beside the River',
    category: 'landscape',
    collectionCategory: 'Imaginary Memories',
    year: '2026',
    medium: 'Oil and Beeswax on Canvas',
    size: '130 x 90 cm',
    dimensions: '130 x 90 cm',
    description: 'A glowing, solitary wooden cottage nestled on the banks of a winding twilight river reflecting a deep sky.',
    story: 'The archetypal home of our dreams—a safe haven of light and peace, sitting at the intersection of land and flowing water.',
    storyBehindPainting: 'This is the anchor of my Imaginary Memories collection. The house is painted with warm, glowing impasto windows, reflecting in the cold, calm water of the winding river.',
    artistReflection: 'We all have a house beside a river in our minds. It is the place we escape to when the world becomes too loud. It is our psychic sanctuary.',
    symbolAnalysis: 'The Cottage is the secure shelter of the self. The River represents the passage of time and the fluid movement of memory.',
    relatedWorks: ['The River That Remembers', 'The Last Lantern'],
    inspirationNotes: 'A cabin in the Bohemian Forest, painted during a week of rainy weather.',
    colorPaletteInfo: 'Prussian Blue, Ultramarine, Cadmium Orange, and Naples Yellow.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)', 'Chelsea Art Collective, New York (2024)'],
    image: '/src/assets/images/river_light_1782341162094.jpg',
    price: '€6,800',
    available: true,
    featured: true,
    colors: ['prussian-blue', 'cadmium-orange', 'raw-sienna'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 4 — PHILOSOPHICAL COLLECTION
  {
    id: 'shadow-owe-light',
    title: 'What Does a Shadow Owe the Light?',
    category: 'abstract',
    collectionCategory: 'Philosophical Collection',
    year: '2026',
    medium: 'Oil on Canvas (Chiaroscuro Study)',
    size: '110 x 110 cm',
    dimensions: '110 x 110 cm',
    description: 'A deep, dramatic abstract canvas exploring the borderline where absolute black shadows meet brilliant white light.',
    story: 'A philosophical exploration of duality. It argues that our shadows are not our enemies, but are defined by our lights.',
    storyBehindPainting: 'This work uses a high-contrast palette of charcoal black and warm alabaster white. The textures are thick and rough at the boundaries, representing the struggle between opposing forces.',
    artistReflection: 'Without light, there are no shadows. Our flaws, our secrets, and our griefs are only visible because we have a soul that glows. We should honor both.',
    symbolAnalysis: 'The Shadow is the subconscious self, while the Light represents awareness, consciousness, and divine inspiration.',
    relatedWorks: ['The Distance Between Versions of Me', 'Metacognition'],
    inspirationNotes: 'Reading Carl Jung’s writings on the integration of the shadow archetype.',
    colorPaletteInfo: 'Carbon Black, Zinc White, Titanium White, and a glaze of Raw Sienna.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/sea_cliff_1782318218612.jpg', // sea cliff acts as high contrast cliffs/shadow
    price: '€5,500',
    available: true,
    featured: false,
    colors: ['prussian-blue', 'titanium-white', 'raw-sienna'],
    roomSimulatorCompatible: true
  },
  {
    id: 'cost-of-becoming',
    title: 'The Cost of Becoming',
    category: 'abstract',
    collectionCategory: 'Philosophical Collection',
    year: '2026',
    medium: 'Oil and Gilded Wax on Linen',
    size: '100 x 120 cm',
    dimensions: '100 x 120 cm',
    description: 'A stylized, textured staircase ascending through clouds into a blinding golden light, with gold flakes peeling off the steps.',
    story: 'A visual metaphor for the sacrifices, pain, and ultimate beauty involved in personal growth and transformation.',
    storyBehindPainting: 'Each step on this staircase is painted with heavy impasto and genuine gold leaf. Towards the bottom, the steps look worn and crumbling; towards the top, they merge into pure glowing energy.',
    artistReflection: 'Growth is always expensive. We must leave behind parts of ourselves we loved in order to step into our true calling. The gold peeling off is the cost we gladly pay.',
    symbolAnalysis: 'The Staircase represents spiritual ascension. The Golden Flakes are the discarded pieces of the ego, and the Light is the ultimate self-realization.',
    relatedWorks: ['The Shape of Regret', 'Self-Awareness'],
    inspirationNotes: 'Written on a studio wall: "To become what you are, you must first un-become what you were taught."',
    colorPaletteInfo: 'Titanium White, Raw Sienna, Gold Powder, and Ivory Black.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/artist_studio_1782318266342.jpg', // studio stairs matching
    price: '€6,300',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'titanium-white', 'prussian-blue'],
    roomSimulatorCompatible: true
  },
  {
    id: 'shape-of-regret',
    title: 'The Shape of Regret',
    category: 'abstract',
    collectionCategory: 'Philosophical Collection',
    year: '2025',
    medium: 'Oil and Stone Powder on Canvas',
    size: '95 x 115 cm',
    dimensions: '95 x 115 cm',
    description: 'A solemn, heavy composition showing a weathered stone sculpture of a head partially dissolving into rainy urban shadows.',
    story: 'Exploring the persistent, heavy architecture that regret builds in the human mind, like stone weathered by endless rain.',
    storyBehindPainting: 'I mixed real marble dust with my oil paints to give the central form a heavy, gritty, geological weight. It sits in a rain-slicked city setting, representing frozen history in a fluid world.',
    artistReflection: 'Regret is like stone. It feels unchangeable. But like stone, it can be sculpted and shaped by time into a monument of quiet wisdom.',
    symbolAnalysis: 'The Stone Head represents memory and intellectual rigidity. The Rain is the passage of time and emotional purification.',
    relatedWorks: ['When the Noise Finally Stopped', 'The Cost of Becoming'],
    inspirationNotes: 'Inspired by the ancient stone statues of Prague standing silent in the winter rain.',
    colorPaletteInfo: 'Raw Umber, Slate Grey, Prussian Blue, and Titanium White.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)'],
    image: '/src/assets/images/city_rain_1782318233879.jpg', // city rain matching
    price: '€4,200',
    available: false,
    featured: false,
    colors: ['prussian-blue', 'titanium-white', 'raw-sienna'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 5 — SEASONS OF A LIFE
  {
    id: 'first-window',
    title: 'The First Window',
    category: 'still-life',
    collectionCategory: 'Seasons of a Life',
    year: '2026',
    medium: 'Oil on Gessoed Panel',
    size: '70 x 70 cm',
    dimensions: '70 x 70 cm',
    description: 'A cozy window frame holding a single candle, looking out at the first quiet snowfall over a sleeping forest.',
    story: 'Capturing the innocent wonder of childhood—the first time we looked out at a changed, silent world from a warm refuge.',
    storyBehindPainting: 'The candle flame is painted with a tiny dab of pure Cadmium Orange, which glows intensely against the cold Prussian Blue and Titanium White of the snow-covered window pane.',
    artistReflection: 'Memory is a window. We are always looking back through the glass of our early years, searching for that original warmth and simplicity.',
    symbolAnalysis: 'The Window represents the boundary between internal reflection and external reality. The Candle stands for hope and the soul’s warmth.',
    relatedWorks: ['Winter Lessons', 'Returning Home'],
    inspirationNotes: 'A memory of my childhood home in Bohemia during the first snowstorm of December.',
    colorPaletteInfo: 'Titanium White, Prussian Blue, Burnt Sienna, and Cadmium Orange.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/chair_lantern_1782341132046.jpg', // interior candles style
    price: '€3,900',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'winter-lessons',
    title: 'Winter Lessons',
    category: 'landscape',
    collectionCategory: 'Seasons of a Life',
    year: '2025',
    medium: 'Oil on Linen (Heavy Impasto)',
    size: '120 x 80 cm',
    dimensions: '120 x 80 cm',
    description: 'A stark, majestic winter forest of snow-laden branches, with a solitary figure walking along a path into a misty white depth.',
    story: 'A visual study of the seasons of rest, endurance, and the necessary wintering of the human spirit.',
    storyBehindPainting: 'I wanted the snow to feel physical, so I used heavy impasto layers of marble dust and oil paint to build deep ridges on the tree branches. The figure is a small, quiet stroke of raw umber.',
    artistReflection: 'Winter is not a punishment; it is a preparation. Trees do not die in winter; they rest. We must also learn the art of resting and enduring in the cold times.',
    symbolAnalysis: 'The Winter Forest is the landscape of patience and preservation. The Path represents the ongoing journey of life despite adversity.',
    relatedWorks: ['Whispers of the Gilded Birch', 'The House Beside the River'],
    inspirationNotes: 'Sketched during a winter trek in the Sumava mountains, breathing cold air.',
    colorPaletteInfo: 'Flake White, Prussian Blue, Cobalt Blue, and Raw Umber.',
    exhibitionHistory: ['Chiaroscuro & Solitude, London (2025)'],
    image: '/src/assets/images/autumn_forest_1782318199839.jpg', // forest theme matching
    price: '€4,750',
    available: true,
    featured: false,
    colors: ['titanium-white', 'viridian-green', 'raw-sienna'],
    roomSimulatorCompatible: true
  },
  {
    id: 'returning-home',
    title: 'Returning Home',
    category: 'landscape',
    collectionCategory: 'Seasons of a Life',
    year: '2026',
    medium: 'Oil and Gilded Wax on Canvas',
    size: '110 x 90 cm',
    dimensions: '110 x 90 cm',
    description: 'A warm country road at dusk, with street lanterns glowing and guiding the path towards a distant, welcoming village.',
    story: 'The comforting feeling of returning to our roots, our origins, and finding that the lights are still burning for us.',
    storyBehindPainting: 'The sky is a deep twilight blue transitioning to warm gold on the horizon. The road is carved with a palette knife, catching the lantern light with genuine gold-leaf sparks.',
    artistReflection: 'No matter how far we travel, there is always a path that leads back to where we started. Home is not a physical house; it is the place where our story makes sense.',
    symbolAnalysis: 'The Glowing Lanterns represent guidance and family ancestry. The Road is the path of life, and the Village is the ultimate reunion.',
    relatedWorks: ['The House Beside the River', 'The Last Lantern'],
    inspirationNotes: 'Listening to traditional Czech folk songs, reflecting on the simplicity of rustic life.',
    colorPaletteInfo: 'Genuine Gold Leaf, Prussian Blue, Cadmium Orange, and Raw Sienna.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/river_light_1782341162094.jpg', // twilight road/river style
    price: '€5,300',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'cadmium-orange', 'prussian-blue'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 6 — HIDDEN LORE
  {
    id: 'last-lantern',
    title: 'The Last Lantern',
    category: 'landscape',
    collectionCategory: 'Hidden Lore',
    year: '2026',
    medium: 'Oil on Canvas (Heavy Impasto)',
    size: '100 x 80 cm',
    dimensions: '100 x 80 cm',
    description: 'A lone traveler holding a glowing iron lantern in a dark, thick forest of towering trees, carving a circle of warm light.',
    story: 'Representing the spark of hope, reason, and individual consciousness carried through the vast, unknowable mysteries of existence.',
    storyBehindPainting: 'This painting centers around the contrast between the dark, menacing forest and the tiny, defiant circle of light. The lantern is built with thick, raised layers of golden-orange paint.',
    artistReflection: 'The forest is deep and full of shadows. It is easy to feel small and lost. But a single lantern is enough to conquer the dark. You do not need to light the whole woods; you only need to light your next step.',
    symbolAnalysis: 'The Lantern represents individual consciousness and hope. The Forest is the vast unconscious mind, and the Traveler is the seeking soul.',
    relatedWorks: ['Inheritance of Silence', 'The River That Remembers'],
    inspirationNotes: 'Written on a napkin: "Carry your own light, and the path will find you."',
    colorPaletteInfo: 'Ivory Black, Viridian Green, Cadmium Orange, and Raw Sienna.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/chair_lantern_1782341132046.jpg', // lantern style matching
    price: '€4,500',
    available: true,
    featured: true,
    colors: ['raw-sienna', 'cadmium-orange', 'viridian-green'],
    roomSimulatorCompatible: true
  },
  {
    id: 'river-remembers',
    title: 'The River That Remembers',
    category: 'landscape',
    collectionCategory: 'Hidden Lore',
    year: '2025',
    medium: 'Oil and Beeswax on Linen',
    size: '130 x 95 cm',
    dimensions: '130 x 95 cm',
    description: 'A deep winding river cutting through dark valley cliffs, reflecting a twilight sky dotted with glowing golden stars.',
    story: 'Exploring the flow of time and memory. The river acts as a geological recording of everything that has occurred on its banks.',
    storyBehindPainting: 'I used deep Prussian Blue glazes to paint the water, building up translucent depths with beeswax. Gold powder was mixed into the glaze to capture the stellar reflections.',
    artistReflection: 'Water is the original mirror of humanity. It flows, yet it remains. It carries our tears, our histories, and our dreams down to the vast, forgiving ocean.',
    symbolAnalysis: 'The River represents the flowing passage of time. The Cliffs represent the solid structure of history, and the Starry Sky represents the infinite cosmos.',
    relatedWorks: ['The House Beside the River', 'The Third Watch'],
    inspirationNotes: 'Sketched on the banks of the Vltava River at 3 AM during a cold spring morning.',
    colorPaletteInfo: 'Prussian Blue, Cerulean Blue, Gold Powder, and Titanium White.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)', 'Chelsea Art Collective, New York (2024)'],
    image: '/src/assets/images/river_light_1782341162094.jpg',
    price: '€5,900',
    available: true,
    featured: false,
    colors: ['prussian-blue', 'titanium-white', 'raw-sienna'],
    roomSimulatorCompatible: true
  },
  {
    id: 'bird-of-gold',
    title: 'The Bird of Gold',
    category: 'abstract',
    collectionCategory: 'Hidden Lore',
    year: '2026',
    medium: 'Oil and 24k Gold Leaf on Linen',
    size: '80 x 80 cm',
    dimensions: '80 x 80 cm',
    description: 'A small, ethereal bird with glowing gold feathers perched on the hands of an old grandfather clock in a shadowed room.',
    story: 'A highly symbolic masterpiece showing hope perched directly on the jaws of time and mortality.',
    storyBehindPainting: 'This is the pinnacle of the Hidden Lore series. The bird is rendered with real 24k gold leaf, which catches the ambient room light in the gallery and literally glows.',
    artistReflection: 'Time is a cage. It binds us to our bodies and our ages. But hope—represented by this tiny golden bird—can perch on the very mechanism of time and sing.',
    symbolAnalysis: 'The Golden Bird stands for transcendence, hope, and the indestructible spirit. The Grandfather Clock is mortality and earthly limits.',
    relatedWorks: ['Borrowed Time', 'The Fire That Refused to Consume'],
    inspirationNotes: 'A response to Hans Christian Andersen’s story of the Nightingale, exploring real vs artificial beauty.',
    colorPaletteInfo: 'Genuine Gold Leaf, Raw Sienna, Burnt Umber, and Charcoal Black.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/bird_clock_1782341148172.jpg',
    price: '€7,500',
    available: true,
    featured: true,
    colors: ['raw-sienna', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 7 — ABSTRACT CONCEPTS
  {
    id: 'metacognition',
    title: 'Metacognition',
    category: 'abstract',
    collectionCategory: 'Abstract Concepts',
    year: '2026',
    medium: 'Oil and Mixed Media on Canvas',
    size: '110 x 110 cm',
    dimensions: '110 x 110 cm',
    description: 'A complex, multi-layered abstract cubist head constructed from interlocking slate plates and glowing gold veins.',
    story: 'A visual translation of self-reflection—the mind turning inward to observe its own processes and patterns.',
    storyBehindPainting: 'I combined oil paint, sand, and marble dust to create heavy, slate-like plates. I then scraped golden veins between these plates, showing the lightning-fast flashes of thought.',
    artistReflection: 'To think about thinking is the defining human trait. It is like looking into a mirror that contains another mirror. It is beautiful and terrifying.',
    symbolAnalysis: 'The Cubist Slate Head is the intellectual vessel. The Glowing Gold Veins represent the firing of self-awareness and creative synapses.',
    relatedWorks: ['Pattern Recognition', 'Self-Awareness'],
    inspirationNotes: 'Inspired by cybernetics, cognitive psychology, and the structured lines of cubist master Georges Braque.',
    colorPaletteInfo: 'Slate Grey, Carbon Black, Genuine Gold Powder, and Titanium White.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/artist_studio_1782318266342.jpg', // abstract studio geometry
    price: '€6,600',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'titanium-white', 'prussian-blue'],
    roomSimulatorCompatible: true
  },
  {
    id: 'pattern-recognition',
    title: 'Pattern Recognition',
    category: 'abstract',
    collectionCategory: 'Abstract Concepts',
    year: '2025',
    medium: 'Oil and Gold Thread on Canvas',
    size: '100 x 100 cm',
    dimensions: '100 x 100 cm',
    description: 'An expansive cosmic dark blue canvas woven with an intricate network of interconnected glowing golden coordinates and stars.',
    story: 'Exploring the human brain’s obsession with finding meaning, geometry, and constellation lines in the chaotic universe.',
    storyBehindPainting: 'The background is a deep, velvety Prussian Blue built up in twelve thin glazes. I then painted a web of fine, glowing lines connecting random star-like spots of Cadmium Orange.',
    artistReflection: 'We look at the stars and see hunters, bears, and scales. We look at life and search for destiny. We are weavers of meaning, and this painting is the loom.',
    symbolAnalysis: 'The Dark Blue Cosmos represents chaotic existence. The Gold Coordinates represent human intellect, science, and the search for spiritual order.',
    relatedWorks: ['Metacognition', 'What If Time Pooled Like Water?'],
    inspirationNotes: 'Sketched while reading articles on quantum entanglement, listening to ambient synthesizer music.',
    colorPaletteInfo: 'Prussian Blue, Cobalt Blue, Cadmium Orange, and Gold Pigment.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)'],
    image: '/src/assets/images/sea_cliff_1782318218612.jpg', // cosmic cliff/sky theme
    price: '€5,800',
    available: true,
    featured: false,
    colors: ['prussian-blue', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'self-awareness',
    title: 'Self-Awareness',
    category: 'abstract',
    collectionCategory: 'Abstract Concepts',
    year: '2026',
    medium: 'Oil and Gilded Beeswax on Linen',
    size: '120 x 120 cm',
    dimensions: '120 x 120 cm',
    description: 'An elegant composition showing a single silhouetted figure walking through a magnificent glowing circular portal of light.',
    story: 'The ultimate arrival of the self—stepping through the threshold of ego into absolute, quiet presence.',
    storyBehindPainting: 'The circular portal is carved out of the surrounding dark Prussian Blue shadow, using concentric rings of Yellow Ochre and Titanium White that rise in heavy texture.',
    artistReflection: 'Awareness is a portal. When you step through, you realize that you are not the thoughts or the body; you are the space in which they exist. You are the light.',
    symbolAnalysis: 'The Circular Portal is the doorway to infinity. The Silhouetted Figure is the traveler, and the light is pure consciousness.',
    relatedWorks: ['The Distance Between Versions of Me', 'The Cost of Becoming'],
    inspirationNotes: 'Inspired by Zen meditation practices and the concept of the Enso circle.',
    colorPaletteInfo: 'Prussian Blue, Naples Yellow, Titanium White, and gold dust.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/river_light_1782341162094.jpg', // twilight portal river theme
    price: '€7,000',
    available: true,
    featured: true,
    colors: ['prussian-blue', 'raw-sienna', 'titanium-white'],
    roomSimulatorCompatible: true
  },

  // CATEGORY 8 — WHAT IF?
  {
    id: 'memories-had-weight',
    title: 'What If Memories Had Weight?',
    category: 'abstract',
    collectionCategory: 'What If?',
    year: '2026',
    medium: 'Oil and Pumice Stone on Canvas',
    size: '120 x 100 cm',
    dimensions: '120 x 100 cm',
    description: 'A dreamlike canvas showing giant, textured floating stone boulders suspended in a misty golden-hour sky, anchored by thin golden chains.',
    story: 'A surrealist query exploring the physical weight of nostalgia and the emotional gravity of the past on our current actions.',
    storyBehindPainting: 'I added pumice stone and coarse sand to my oils to make the floating boulders look unbelievably heavy, textured, and rough, contrasting with the ethereal, soft sky around them.',
    artistReflection: 'If memories had weight, some of us would be crushed under our own childhoods. Others would float away. This painting is about the chains of light that keep us anchored.',
    symbolAnalysis: 'The Suspended Boulders represent heavy, preserved memories. The Golden Chains are the emotional connections that keep us grounded to our history.',
    relatedWorks: ['The Weight of Unspoken Words', 'What If Time Pooled Like Water?'],
    inspirationNotes: 'Inspired by the surreal landscapes of René Magritte, reinterpreted with a heavy tactile oil style.',
    colorPaletteInfo: 'Raw Sienna, Slate Grey, Naples Yellow, and Burnt Umber.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/autumn_forest_1782318199839.jpg', // heavy tree trunks look like boulders/pillars
    price: '€6,400',
    available: true,
    featured: false,
    colors: ['raw-sienna', 'titanium-white', 'viridian-green'],
    roomSimulatorCompatible: true
  },
  {
    id: 'time-pooled-water',
    title: 'What If Time Pooled Like Water?',
    category: 'abstract',
    collectionCategory: 'What If?',
    year: '2025',
    medium: 'Oil and Beeswax on Canvas',
    size: '115 x 115 cm',
    dimensions: '115 x 115 cm',
    description: 'A melting clock face dissolving into a deep twilight tide pool, with waves of gold light swirling inside the water.',
    story: 'Exploring a world where time is not a linear arrow, but a fluid pool where past, present, and future coexist and swirl together.',
    storyBehindPainting: 'Painted with thick translucent layers of beeswax, giving the tide pool a real, glassy depth. The clock numbers are painted with glowing gold leaf and are swirling into the vortex.',
    artistReflection: 'We are obsessed with schedules and clocks. But memory proves that time is fluid. A moment from twenty years ago can feel closer than yesterday. Time pools in our hearts.',
    symbolAnalysis: 'The Tide Pool represents the fluid heart. The Melting Clock represents the dissolving of temporal limits, and the Gold Light is eternal presence.',
    relatedWorks: ['Borrowed Time', 'The River That Remembers'],
    inspirationNotes: 'Listening to Erik Satie’s Gymnopédies while glazing the deep blue tide pool layers.',
    colorPaletteInfo: 'Prussian Blue, Cobalt Blue, Gold Leaf, and Naples Yellow.',
    exhibitionHistory: ['Atmospheric Mirrors, Paris (2026)', 'Chelsea Art Collective, New York (2024)'],
    image: '/src/assets/images/river_light_1782341162094.jpg', // twilight water pool
    price: '€6,900',
    available: true,
    featured: false,
    colors: ['prussian-blue', 'raw-sienna', 'titanium-white'],
    roomSimulatorCompatible: true
  },
  {
    id: 'hope-emitted-light',
    title: 'What If Hope Emitted Light?',
    category: 'abstract',
    collectionCategory: 'What If?',
    year: '2026',
    medium: 'Oil and Gold Leaf on Linen',
    size: '110 x 110 cm',
    dimensions: '110 x 110 cm',
    description: 'A magical chiaroscuro canvas showing a small child holding a tiny, blindingly radiant glowing golden spark in her hands.',
    story: 'An emotional exploration of hope as a physical, luminescent particle that can light up the deepest human darkness.',
    storyBehindPainting: 'The child is a soft, dark silhouette in deep shadow, while her hands hold a heavily sculpted impasto star of gold leaf and Titanium White that casts brilliant physical rays of light across her face.',
    artistReflection: 'Hope is not a passive wish. It is an active power. If we could see it under a microscope, I believe it would be a tiny sun, glowing with energy and warming the surrounding cold.',
    symbolAnalysis: 'The Child represents innocence and openness. The Glowing Spark is the physical particle of hope, and the Chiaroscuro darkness represents life’s trials.',
    relatedWorks: ['The Bird of Gold', 'The Last Lantern'],
    inspirationNotes: 'Inspired by a candle lit in a dark cathedral in Prague during a winter storm.',
    colorPaletteInfo: 'Genuine Gold Leaf, Burnt Umber, Ivory Black, and Titanium White.',
    exhibitionHistory: ['The Texture of Light, Milan (2026)'],
    image: '/src/assets/images/bird_clock_1782341148172.jpg', // bird clock acts as high contrast glow
    price: '€7,800',
    available: true,
    featured: true,
    colors: ['raw-sienna', 'cadmium-orange', 'titanium-white'],
    roomSimulatorCompatible: true
  }
];

export const PALETTE_COLORS: PaletteColor[] = [
  {
    id: 'prussian-blue',
    name: 'Prussian Blue',
    hex: '#102E4A',
    symbolicMeaning: 'Depth, melancholy, and oceanic shadows. James Ricardo uses this color as the foundation for night skies, deep water, and the dark architectural forms of cities.',
    quote: 'Prussian Blue is the color of memories. It holds the shadow of every wave and the weight of night on its shoulders.',
    associatedArtworks: ['distance-between-versions', 'noise-stopped', 'third-watch', 'last-train-summer', 'house-beside-river', 'shadow-owe-light', 'shape-of-regret', 'river-remembers', 'pattern-recognition', 'self-awareness', 'time-pooled-water']
  },
  {
    id: 'cadmium-orange',
    name: 'Cadmium Orange',
    hex: '#E06D3B',
    symbolicMeaning: 'Vitality, warm light piercing through darkness, and electric energy. It acts as the emotional spark in both natural landscapes and urban reflections.',
    quote: 'A spark of Cadmium Orange is a whisper of fire in a silent canvas. It creates a sudden, electric vibration of life.',
    associatedArtworks: ['borrowed-time', 'inheritance-silence', 'noise-stopped', 'fire-refused-consume', 'last-train-summer', 'house-beside-river', 'before-rooster-crowed', 'first-window', 'returning-home', 'last-lantern', 'bird-of-gold', 'pattern-recognition', 'hope-emitted-light']
  },
  {
    id: 'raw-sienna',
    name: 'Raw Sienna',
    hex: '#D1A153',
    symbolicMeaning: 'The connection to earth, ancient soil, and the warm, grounded glow of stone and light. It provides organic warmth and anchors high-contrast lighting.',
    quote: 'Raw Sienna ties the sky to the soil. It is the color of ancient dust illuminated by a low, golden-hour sun.',
    associatedArtworks: ['distance-between-versions', 'borrowed-time', 'inheritance-silence', 'weight-unspoken', 'third-watch', 'before-rooster-crowed', 'fire-refused-consume', 'last-train-summer', 'letters-never-delivered', 'house-beside-river', 'shadow-owe-light', 'cost-of-becoming', 'shape-of-regret', 'first-window', 'winter-lessons', 'returning-home', 'last-lantern', 'river-remembers', 'bird-of-gold', 'metacognition', 'self-awareness', 'memories-had-weight', 'time-pooled-water', 'hope-emitted-light']
  },
  {
    id: 'viridian-green',
    name: 'Viridian Green',
    hex: '#1E5E4E',
    symbolicMeaning: 'The breathing vitality of botanical life. It captures the moist, fresh dampness of moss, forest foliage, and deep mountain shadows.',
    quote: 'Viridian contains the breathing lung of the forest. It carries the rich, damp aroma of organic soil after rain.',
    associatedArtworks: ['weight-unspoken', 'fire-refused-consume', 'winter-lessons', 'last-lantern', 'memories-had-weight']
  },
  {
    id: 'titanium-white',
    name: 'Titanium White',
    hex: '#F7F4EB',
    symbolicMeaning: 'Luminosity, pure light, and open air. It is used in impasto ridges to physically catch gallery spotlights, creating real shadows on the painted surface.',
    quote: 'White is not the absence of color; it is the collision of all colors reflecting back at us. It is where the canvas breathes.',
    associatedArtworks: ['distance-between-versions', 'inheritance-silence', 'noise-stopped', 'weight-unspoken', 'third-watch', 'before-rooster-crowed', 'fire-refused-consume', 'letters-never-delivered', 'shadow-owe-light', 'cost-of-becoming', 'shape-of-regret', 'first-window', 'winter-lessons', 'river-remembers', 'bird-of-gold', 'metacognition', 'pattern-recognition', 'self-awareness', 'memories-had-weight', 'time-pooled-water', 'hope-emitted-light']
  }
];

export const EXHIBITIONS: Exhibition[] = [
  {
    id: 'exh-1',
    title: 'The Texture of Light',
    gallery: 'Galleria d’Arte Moderna',
    city: 'Milan, Italy',
    year: '2026',
    date: 'Oct 12 – Nov 30, 2026',
    status: 'upcoming',
    description: 'A solo retrospective showcasing James Ricardo’s newest landscape and ocean studies, focusing on the sensory relationship between paint texture, light refraction, and physical environment.'
  },
  {
    id: 'exh-2',
    title: 'Atmospheric Mirrors',
    gallery: 'Galerie de l’Est',
    city: 'Paris, France',
    year: '2026',
    date: 'Mar 05 – Apr 20, 2026',
    status: 'current',
    description: 'An exhibition exploring urban nightscapes, wet asphalt reflections, and the emotional resonance of rain. Featuring her highly acclaimed Berlin and Paris series.'
  },
  {
    id: 'exh-3',
    title: 'Chiaroscuro & Solitude',
    gallery: 'The Somerset Fine Art Gallery',
    city: 'London, UK',
    year: '2025',
    date: 'Sep 10 – Oct 15, 2025',
    status: 'past',
    description: 'A curated showcase of minimalist still life paintings and intimate interior portraits, drawing comparisons to Dutch golden age light masters.'
  },
  {
    id: 'exh-4',
    title: 'Crashing and Stillness',
    gallery: 'Chelsea Art Collective',
    city: 'New York, USA',
    year: '2024',
    date: 'May 02 – Jun 15, 2024',
    status: 'past',
    description: 'James Ricardo’s inaugural US solo show, focusing on the dramatic juxtaposition of restless coastal seascapes and calm, monumental cliffs.'
  }
];

export const AWARDS: Award[] = [
  {
    year: '2025',
    title: 'Lorenzo il Magnifico Gold Medal (Painting)',
    event: 'Florence Biennale, Italy'
  },
  {
    year: '2024',
    title: 'Artist of the Future Award',
    event: 'Contemporary Art Review, London'
  },
  {
    year: '2023',
    title: 'First Prize in Landscape Studies',
    event: 'National Oil Painters Guild'
  }
];

export const ARTIST_BIOGRAPHY = {
  name: 'James Ricardo',
  title: 'Contemporary Painter',
  birthplace: 'Prague, Czech Republic',
  studio: '/src/assets/images/artist_studio_1782318266342.jpg',
  statement: `My paintings explore the borderland between reality and abstract emotional memory. I do not paint places or objects as they exist in sterile space; instead, I paint the tactile residue they leave on our senses. 

Through thick impasto palette knife marks, translucent oil glazes, and physical layers of paint and beeswax, I seek to turn light into something you can touch. Each painting is an archaeological excavation of a single sensory moment—the cold spray of seawater against a cliff, the sudden warmth of a neon reflection on a wet Berlin street, or the quiet, meditative solitude of a piece of fruit sitting in a shaft of morning light.`,
  methods: [
    {
      title: 'Heavy Impasto Layering',
      description: 'Using steel palette knives to sculpt heavy layers of oil paint, creating raw textures that rise off the canvas and cast physical shadows under room lighting.'
    },
    {
      title: 'Beeswax Glazing',
      description: 'Blending pure pharmaceutical beeswax with fine oil pigments to achieve a deep, satiny, translucent quality that captures and holds light inside the canvas layers.'
    },
    {
      title: 'Plein Air Exploration',
      description: 'Creating rapid watercolor and charcoal studies directly on-site in nature or on city streets to capture immediate light and atmospheric moods, before rendering them on large-scale canvases in the studio.'
    }
  ]
};
